program: main.py
method: grid
parameters:
  gnn_type:
    value: 'sort'
  num_layer:
    values: [5]
  emb_dim:
    value: 60
  batch_size:
    value: 128
  learning_rate:
    values: [0.01]
  epochs:
    value: 400
  dataset:
    value: 'ZINC'
  jk:
    values: ['sum']
  drop_ratio:
    value: 0.
  channels:
    values: ['96']
  policy:
    values: ['ego_nets_plus', 'ego_nets', 'edge_deleted', 'node_deleted']
  model:
    value: 'dss'
  seed:
    values: [1,2,3,4,5,6,7,8,9,10]
  # sort parameters
  combine:
    values: ['ConcatProject']
  collapse_method:
    values: ['matrix']
  bias:
    values: [True]
  blank_method:
    values: ['learnable']
  custom_readout:
    values: [True]
  relu_edge:
    values: [False]
  grad_clip:
    values: [15]
command:
  - ${interpreter}
  - ${program}
  - ${args_no_boolean_flags}