name: HolderAnalysis
channels:
  - conda-forge
  - defaults
dependencies:
  - fsspec=2024.3.1
  - matplotlib-base=3.8.4
  - numpy=1.26.4
  - openbabel=3.1.1
  - pandas=2.2.2
  - pip=23.3.1
  - python=3.10.13
  - rdkit=2024.03.1

